export default {
  getDescription: (queryId) => {
    const limit = input_limit?.value || 5; 
    
    const descriptions = {
      low_stock: "Shows all medications with stock quantity below 50 units",
      top_staff: `Displays the top ${limit} staff members with most appointments`,
      busiest_day: "Finds the day with highest number of appointments",
      unpaid_bills: `Lists clients with highest unpaid bills (top ${limit})`,
      staff_revenue: "Shows total revenue generated by each staff member",
      diagnoses: "Counts medical records by diagnosis type",
      monthly_records: "Shows medical records issued per month",
      overweight_pets: "Finds pets weighing more than breed average",
      staff_billing: `Top staff by average billing per appointment (top ${limit})`,
      clients_by_breed: "Lists clients who own pets of selected breed",
      pres_by_pet: "Find a specific pet to list all the medical prescriptions of it",
      rx_by_category: "Find all medical records with a diagnosis that matches a specific pattern"
    };
    return descriptions[queryId] || "Select a query to see description";
  }
}